"""Add owner_id

Revision ID: 0c106357b494
Revises: 348fe7dffbaf
Create Date: 2024-10-24 10:44:05.101506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c106357b494'
down_revision: Union[str, None] = '348fe7dffbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('owner_id', sa.String(), nullable=False))
    op.add_column('pipelines', sa.Column('owner_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'owner_id')
    op.drop_column('artifacts', 'owner_id')
    # ### end Alembic commands ###
