"""add connection logic

Revision ID: 19caff278618
Revises: b9bbbab976a3
Create Date: 2024-09-13 14:45:15.204008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19caff278618'
down_revision: Union[str, None] = 'b9bbbab976a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('connection_pipeline_left_id_fkey', 'connection_pipeline', type_='foreignkey')
    op.drop_constraint('connection_pipeline_right_id_fkey', 'connection_pipeline', type_='foreignkey')
    op.create_foreign_key(None, 'connection_pipeline', 'connections', ['left_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connection_pipeline', 'pipelines', ['right_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('connection_sourceartifact_left_id_fkey', 'connection_sourceartifact', type_='foreignkey')
    op.drop_constraint('connection_sourceartifact_right_id_fkey', 'connection_sourceartifact', type_='foreignkey')
    op.create_foreign_key(None, 'connection_sourceartifact', 'artifacts', ['right_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connection_sourceartifact', 'connections', ['left_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('connection_targetartifact_left_id_fkey', 'connection_targetartifact', type_='foreignkey')
    op.drop_constraint('connection_targetartifact_right_id_fkey', 'connection_targetartifact', type_='foreignkey')
    op.create_foreign_key(None, 'connection_targetartifact', 'connections', ['left_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connection_targetartifact', 'artifacts', ['right_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connection_targetartifact', type_='foreignkey')
    op.drop_constraint(None, 'connection_targetartifact', type_='foreignkey')
    op.create_foreign_key('connection_targetartifact_right_id_fkey', 'connection_targetartifact', 'artifacts', ['right_id'], ['id'])
    op.create_foreign_key('connection_targetartifact_left_id_fkey', 'connection_targetartifact', 'connections', ['left_id'], ['id'])
    op.drop_constraint(None, 'connection_sourceartifact', type_='foreignkey')
    op.drop_constraint(None, 'connection_sourceartifact', type_='foreignkey')
    op.create_foreign_key('connection_sourceartifact_right_id_fkey', 'connection_sourceartifact', 'artifacts', ['right_id'], ['id'])
    op.create_foreign_key('connection_sourceartifact_left_id_fkey', 'connection_sourceartifact', 'connections', ['left_id'], ['id'])
    op.drop_constraint(None, 'connection_pipeline', type_='foreignkey')
    op.drop_constraint(None, 'connection_pipeline', type_='foreignkey')
    op.create_foreign_key('connection_pipeline_right_id_fkey', 'connection_pipeline', 'pipelines', ['right_id'], ['id'])
    op.create_foreign_key('connection_pipeline_left_id_fkey', 'connection_pipeline', 'connections', ['left_id'], ['id'])
    # ### end Alembic commands ###
