"""fix ondelete behavior

Revision ID: 27a743c1b232
Revises: a54edcd3be78
Create Date: 2024-09-13 10:24:27.827132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a743c1b232'
down_revision: Union[str, None] = 'a54edcd3be78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artifact_pipelines_right_id_fkey', 'artifact_pipelines', type_='foreignkey')
    op.create_foreign_key(None, 'artifact_pipelines', 'pipelines', ['right_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifact_pipelines', type_='foreignkey')
    op.create_foreign_key('artifact_pipelines_right_id_fkey', 'artifact_pipelines', 'pipelines', ['right_id'], ['id'])
    # ### end Alembic commands ###
