"""add artifact type to dagdb data

Revision ID: a12f1b78beca
Revises: 19caff278618
Create Date: 2024-09-17 18:00:32.333570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12f1b78beca'
down_revision: Union[str, None] = '19caff278618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('artifact_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'artifact_type')
    # ### end Alembic commands ###
