"""fix ondelete behavior

Revision ID: a54edcd3be78
Revises: 204e81d9f5a4
Create Date: 2024-09-13 10:16:13.714219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54edcd3be78'
down_revision: Union[str, None] = '204e81d9f5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artifact_pipelines_left_id_fkey', 'artifact_pipelines', type_='foreignkey')
    op.create_foreign_key(None, 'artifact_pipelines', 'artifacts', ['left_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'artifacts', ['id'])
    op.create_unique_constraint(None, 'connections', ['id'])
    op.create_unique_constraint(None, 'pipelines', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipelines', type_='unique')
    op.drop_constraint(None, 'connections', type_='unique')
    op.drop_constraint(None, 'artifacts', type_='unique')
    op.drop_constraint(None, 'artifact_pipelines', type_='foreignkey')
    op.create_foreign_key('artifact_pipelines_left_id_fkey', 'artifact_pipelines', 'artifacts', ['left_id'], ['id'])
    # ### end Alembic commands ###
