"""Fix on delete behaviour

Revision ID: bd7a3169c1d9
Revises: 0c106357b494
Create Date: 2024-11-02 19:31:56.381714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7a3169c1d9'
down_revision: Union[str, None] = '0c106357b494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artifact_pipelines_left_id_fkey', 'artifact_pipelines', type_='foreignkey')
    op.drop_constraint('artifact_pipelines_right_id_fkey', 'artifact_pipelines', type_='foreignkey')
    op.create_foreign_key(None, 'artifact_pipelines', 'pipelines', ['right_id'], ['id'])
    op.create_foreign_key(None, 'artifact_pipelines', 'artifacts', ['left_id'], ['id'])
    op.drop_constraint('connection_pipeline_left_id_fkey', 'connection_pipeline', type_='foreignkey')
    op.drop_constraint('connection_pipeline_right_id_fkey', 'connection_pipeline', type_='foreignkey')
    op.create_foreign_key(None, 'connection_pipeline', 'pipelines', ['right_id'], ['id'])
    op.create_foreign_key(None, 'connection_pipeline', 'connections', ['left_id'], ['id'])
    op.drop_constraint('connection_sourceartifact_left_id_fkey', 'connection_sourceartifact', type_='foreignkey')
    op.create_foreign_key(None, 'connection_sourceartifact', 'connections', ['left_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('connection_targetartifact_left_id_fkey', 'connection_targetartifact', type_='foreignkey')
    op.create_foreign_key(None, 'connection_targetartifact', 'connections', ['left_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connection_targetartifact', type_='foreignkey')
    op.create_foreign_key('connection_targetartifact_left_id_fkey', 'connection_targetartifact', 'connections', ['left_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'connection_sourceartifact', type_='foreignkey')
    op.create_foreign_key('connection_sourceartifact_left_id_fkey', 'connection_sourceartifact', 'connections', ['left_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'connection_pipeline', type_='foreignkey')
    op.drop_constraint(None, 'connection_pipeline', type_='foreignkey')
    op.create_foreign_key('connection_pipeline_right_id_fkey', 'connection_pipeline', 'pipelines', ['right_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('connection_pipeline_left_id_fkey', 'connection_pipeline', 'connections', ['left_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'artifact_pipelines', type_='foreignkey')
    op.drop_constraint(None, 'artifact_pipelines', type_='foreignkey')
    op.create_foreign_key('artifact_pipelines_right_id_fkey', 'artifact_pipelines', 'pipelines', ['right_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('artifact_pipelines_left_id_fkey', 'artifact_pipelines', 'artifacts', ['left_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
